### PR TITLE
Update sources to the same as cmake_lib

### PR DESCRIPTION
**Pull request by czoido**
Seems like is not a problem changing this. Although we link this in the docs as example, looks like we have no examples where we clone this and build it.
This PR is mainly motivated by the fact that we need an external repo with sources to explain certain things in the new tutorial for Conan 2.0. If we merge this it would also be nice to create a 2.0 release.

Needed for this: https://github.com/conan-io/examples2/pull/22

### CODE REVIEW

**Review by memsharded — CHANGES_REQUESTED** [review]
I think this is used in the ``conan new`` legacy template:

```
conan new hello/0.1
```
Will contain:
```python
def source(self):
        self.run("git clone https://github.com/conan-io/hello.git")
```
So it will break.

I think we might need a tag, branch or another repo.

**Comment by czoido** [comment]
> I think this is used in the `conan new` legacy template:
> 
> ```
> conan new hello/0.1
> ```
> 
> Will contain:
> 
> ```python
> def source(self):
>         self.run("git clone https://github.com/conan-io/hello.git")
> ```
> 
> So it will break.
> 
> I think we might need a tag, branch or another repo.

I completely forgot about using conan new without templates. It's not used a lot in the docs, maybe we should remove that from the docs and update all conan new ocurrences to the templates?
But yes, let's create a new repo. What about:
- https://github.com/conan-io/hello-world
- https://github.com/conan-io/hello-library
- https://github.com/conan-io/libhello
- ...

**Comment by memsharded** [comment]
> I completely forgot about using conan new without templates. It's not used a lot in the docs, maybe we should remove that from the docs and update all conan new ocurrences to the templates?

There are like 4 relevant uses of this ``conan new`` in the docs, that will need some further changes to the docs, it is not that the occurrence can be removed, but it should be updated and then fix those docs. Not sure about the effort, but not something immediate and easy.

Any of those names looks good for a new repo, maybe ``libhello``?

**Comment by czoido** [comment]
> > I completely forgot about using conan new without templates. It's not used a lot in the docs, maybe we should remove that from the docs and update all conan new ocurrences to the templates?
> 
> There are like 4 relevant uses of this `conan new` in the docs, that will need some further changes to the docs, it is not that the occurrence can be removed, but it should be updated and then fix those docs. Not sure about the effort, but not something immediate and easy.
> 
> Any of those names looks good for a new repo, maybe `libhello`?

Yes, I'll create the libhello repo and add these sources

**Pull request closed without merging**
